export const GET_USER_LOGIN = 'GET_USER_LOGIN';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const ADD_VISITOR_TYPE_CART = 'ADD_VISITOR_TYPE_CART';
export const REMOVE_VISITORTYPE = 'REMOVE_VISITORTYPE';
export const ADD_VISITOR_TYPE_CART_ALL = 'ADD_VISITOR_TYPE_CART_ALL';
